// @ts-check

/**
 * The whole site is one sidebar, generated from the folder structure of
 * `docs/`. Ordering comes from `sidebar_position` front matter and the
 * `_category_.json` files (including the generated ones under `docs/reference`).
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
